services:
  backend:
    container_name: fox-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
