server.port=8080

spring.datasource.url=jdbc:sqlserver://sqlserver.dev.nfptech.com.br:1433;databaseName=fox;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Aq%N6qD&
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=fox-dev-secret-key-local-2026-minimum-256-bit
jwt.expiration=900000
refresh-token.expiration=604800000
password-reset-token.expiration=900000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174,https://fox.dev.nfptech.com.br}
